server/django_authopenid/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, url
from django.utils.translation import ugettext as _

urlpatterns = patterns('django_authopenid.views',
    # yadis rdf
    url(r'^yadis\.xrdf$', 'xrdf', name='yadis_xrdf'),
     # manage account registration
    url(r'^%s$' % _('signin/'), 'signin', name='user_signin'),
    url(r'^%s$' % _('signout/'), 'signout', name='user_signout'),
    url(r'^%s%s$' % (_('signin/'), _('complete/')), 'complete_signin', 
        name='user_complete_signin'),
    url(r'^%s$' % _('register/'), 'register', name='user_register'),
    url(r'^%s$' % _('signup/'), 'signup', name='user_signup'),
    url(r'^%s$' % _('sendpw/'), 'sendpw', name='user_sendpw'),
    url(r'^%s%s$' % (_('password/'), _('confirm/')), 'confirmchangepw', 
        name='user_confirmchangepw'),

    # manage account settings
    url(r'^$', 'account_settings', name='user_account_settings'),
    url(r'^%s$' % _('password/'), 'changepw', name='user_changepw'),
    url(r'^%s$' % _('email/'), 'changeemail', name='user_changeemail'),
    url(r'^%s$' % _('openid/'), 'changeopenid', name='user_changeopenid'),
    url(r'^%s$' % _('delete/'), 'delete', name='user_delete'),
)

server/urls.py
"""adds ebooks prefix to urls"""
from django.contrib import admin
from django.conf.urls.defaults import *

try:
    from settings import ROOT_URL
except ImportError:
    ROOT_URL = r''

from spec.logger import create_log

create_log()

admin.autodiscover()

urlpatterns = patterns('',
    (ROOT_URL, include('urls_root')),
)

server/django_authopenid/models.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models

import md5, random, sys, os, time

__all__ = ['Nonce', 'Association', 'UserAssociation', 
        'UserPasswordQueueManager', 'UserPasswordQueue']

class Nonce(models.Model):
    """ openid nonce """
    server_url = models.CharField(max_length=255)
    timestamp = models.IntegerField()
    salt = models.CharField(max_length=40)
    
    def __unicode__(self):
        return u"Nonce: %s" % self.id

    
class Association(models.Model):
    """ association openid url and lifetime """
    server_url = models.TextField(max_length=2047)
    handle = models.CharField(max_length=255)
    secret = models.TextField(max_length=255) # Stored base64 encoded
    issued = models.IntegerField()
    lifetime = models.IntegerField()
    assoc_type = models.TextField(max_length=64)
    
    def __unicode__(self):
        return u"Association: %s, %s" % (self.server_url, self.handle)

class UserAssociation(models.Model):
    """ 
    model to manage association between openid and user 
    """
    openid_url = models.CharField(blank=False, max_length=255)
    user = models.ForeignKey(User, unique=True)
    
    def __unicode__(self):
        return "Openid %s with user %s" % (self.openid_url, self.user)
        
class UserAssociationAdmin(admin.ModelAdmin):
    """User association admin class"""
admin.site.register(UserAssociation, UserAssociationAdmin)

class UserPasswordQueueManager(models.Manager):
    """ manager for UserPasswordQueue object """
    def get_new_confirm_key(self):
        "Returns key that isn't being used."
        # The random module is seeded when this Apache child is created.
        # Use SECRET_KEY as added salt.
        while 1:
            confirm_key = md5.new("%s%s%s%s" % (
                random.randint(0, sys.maxint - 1), os.getpid(),
                time.time(), settings.SECRET_KEY)).hexdigest()
            try:
                self.get(confirm_key=confirm_key)
            except self.model.DoesNotExist:
                break
        return confirm_key


class UserPasswordQueue(models.Model):
    """
    model for new password queue.
    """
    user = models.ForeignKey(User, unique=True)
    new_password = models.CharField(max_length=30)
    confirm_key = models.CharField(max_length=40)

    objects = UserPasswordQueueManager()

    def __unicode__(self):
        return self.user.username

server/django_authopenid/forms.py
# -*- coding: utf-8 -*-
# Copyright (c) 2007, 2008, Benoît Chesneau
# 
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
#      * Redistributions of source code must retain the above copyright
#      * notice, this list of conditions and the following disclaimer.
#      * Redistributions in binary form must reproduce the above copyright
#      * notice, this list of conditions and the following disclaimer in the
#      * documentation and/or other materials provided with the
#      * distribution.  Neither the name of the <ORGANIZATION> nor the names
#      * of its contributors may be used to endorse or promote products
#      * derived from this software without specific prior written
#      * permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
# OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.utils.translation import ugettext as _
from django.conf import settings

import re


# needed for some linux distributions like debian
try:
    from openid.yadis import xri
except ImportError:
    from yadis import xri

__all__ = ['OpenidSigninForm', 'OpenidAuthForm', 'OpenidVerifyForm',
        'OpenidRegisterForm', 'RegistrationForm', 'ChangepwForm',
        'ChangeemailForm', 'EmailPasswordForm', 'DeleteForm',
        'ChangeOpenidForm', 'ChangeEmailForm', 'ChangepwForm']

class OpenidSigninForm(forms.Form):
    """ signin form """
    openid_url = forms.CharField(max_length=255, 
            widget=forms.widgets.TextInput(attrs={'class': 'required openid'}))
    next = forms.CharField(max_length=255, widget=forms.HiddenInput(), 
            required=False)

    def clean_openid_url(self):
        """ test if openid is accepted """
        if 'openid_url' in self.cleaned_data:
            openid_url = self.cleaned_data['openid_url']
            if xri.identifierScheme(openid_url) == 'XRI' and getattr(
                settings, 'OPENID_DISALLOW_INAMES', False
                ):
                raise forms.ValidationError(_('i-names are not supported'))
            return self.cleaned_data['openid_url']

    def clean_next(self):
        """ validate next """
        if 'next' in self.cleaned_data and self.cleaned_data['next'] != "":
            next_url_re = re.compile('^/[-\w/]*$')
            if not next_url_re.match(self.cleaned_data['next']):
                raise forms.ValidationError(_('next url "%s" is invalid' % 
                    self.cleaned_data['next']))
            return self.cleaned_data['next']


attrs_dict = { 'class': 'required login' }
username_re = re.compile(r'^\w+$')

class OpenidAuthForm(forms.Form):
    """ legacy account signin form """
    next = forms.CharField(max_length=255, widget=forms.HiddenInput(), 
            required=False)
    username = forms.CharField(max_length=30,  
            widget=forms.widgets.TextInput(attrs=attrs_dict))
    password = forms.CharField(max_length=128, 
            widget=forms.widgets.PasswordInput(attrs=attrs_dict))
       
    def __init__(self, data=None, files=None, auto_id='id_%s',
            prefix=None, initial=None): 
        super(OpenidAuthForm, self).__init__(data, files, auto_id,
                prefix, initial)
        self.user_cache = None
            
    def clean_username(self):
        """ validate username and test if it exists."""
        if 'username' in self.cleaned_data and \
                'openid_url' not in self.cleaned_data:
            if not username_re.search(self.cleaned_data['username']):
                raise forms.ValidationError(_("Usernames can only contain \
                    letters, numbers and underscores"))
            try:
                user = User.objects.get(
                        username__exact = self.cleaned_data['username']
                )
            except User.DoesNotExist:
                raise forms.ValidationError(_("This username does not exist \
                    in our database. Please choose another."))
            return self.cleaned_data['username']

    def clean_password(self):
        """" test if password is valid for this username """
        if 'username' in self.cleaned_data and \
                'password' in self.cleaned_data:
            self.user_cache =  authenticate(
                    username=self.cleaned_data['username'], 
                    password=self.cleaned_data['password']
            )
            if self.user_cache is None:
                raise forms.ValidationError(_("Please enter a valid \
                    username and password. Note that both fields are \
                    case-sensitive."))
            elif self.user_cache.is_active == False:
                raise forms.ValidationError(_("This account is inactive."))
            return self.cleaned_data['password']

    def clean_next(self):
        """ validate next url """
        if 'next' in self.cleaned_data and \
                self.cleaned_data['next'] != "":
            next_url_re = re.compile('^/[-\w/]*$')
            if not next_url_re.match(self.cleaned_data['next']):
                raise forms.ValidationError(
                        _('next url "%s" is invalid' % 
                            self.cleaned_data['next'])
                )
            return self.cleaned_data['next']
            
    def get_user(self):
        """ get authenticated user """
        return self.user_cache
            

class OpenidRegisterForm(forms.Form):
    """ openid signin form """
    next = forms.CharField(max_length=255, widget=forms.HiddenInput(), 
            required=False)
    username = forms.CharField(max_length=30, 
            widget=forms.widgets.TextInput(attrs=attrs_dict))
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict, 
        maxlength=200)), label=u'Email address')
    
    def clean_username(self):
        """ test if username is valid and exist in database """
        if 'username' in self.cleaned_data:
            if not username_re.search(self.cleaned_data['username']):
                raise forms.ValidationError(_("Usernames can only contain \
                    letters, numbers and underscores"))
            try:
                user = User.objects.get(
                        username__exact = self.cleaned_data['username']
                        )
            except User.DoesNotExist:
                return self.cleaned_data['username']
            raise forms.ValidationError(_("This username is already \
                taken. Please choose another."))
            
    def clean_email(self):
        """For security reason one unique email in database"""
        if 'email' in self.cleaned_data:
            try:
                user = User.objects.get(email = self.cleaned_data['email'])
            except User.DoesNotExist:
                return self.cleaned_data['email']
            raise forms.ValidationError(_("This email is already \
                registered in our database. Please choose another."))
 
    
class OpenidVerifyForm(forms.Form):
    """ openid verify form (associate an openid with an account) """
    next = forms.CharField(max_length=255, widget = forms.HiddenInput(), 
            required=False)
    username = forms.CharField(max_length=30, 
            widget=forms.widgets.TextInput(attrs=attrs_dict))
    password = forms.CharField(max_length=128, 
            widget=forms.widgets.PasswordInput(attrs=attrs_dict))
    
    def __init__(self, data=None, files=None, auto_id='id_%s',
            prefix=None, initial=None): 
        super(OpenidVerifyForm, self).__init__(data, files, auto_id,
                prefix, initial)
        self.user_cache = None

    def clean_username(self):
        """ validate username """
        if 'username' in self.cleaned_data:
            if not username_re.search(self.cleaned_data['username']):
                raise forms.ValidationError(_("Usernames can only contain \
                    letters, numbers and underscores"))
            try:
                user = User.objects.get(
                        username__exact = self.cleaned_data['username']
                )
            except User.DoesNotExist:
                raise forms.ValidationError(_("This username don't exist. \
                        Please choose another."))
            return self.cleaned_data['username']
            
    def clean_password(self):
        """ test if password is valid for this user """
        if 'username' in self.cleaned_data and \
                'password' in self.cleaned_data:
            self.user_cache =  authenticate(
                    username = self.cleaned_data['username'], 
                    password = self.cleaned_data['password']
            )
            if self.user_cache is None:
                raise forms.ValidationError(_("Please enter a valid \
                    username and password. Note that both fields are \
                    case-sensitive."))
            elif self.user_cache.is_active == False:
                raise forms.ValidationError(_("This account is inactive."))
            return self.cleaned_data['password']
            

server/django_authopenid/templates/authopenid/changeemail.html
{% extends "base.html" %}
{% load i18n %}




{% block content %}
<h4 class="headblue">{% trans "Account: change email" %}</h4>

<p class="settings-descr">{% blocktrans %}This is where you can change the email address associated with your account. Please keep this email address up to date so we can send you a password-reset email if you request one.{% endblocktrans %}</p>
{% if form.errors %}
<p class="errors">{% trans "Please correct errors below:" %}<br />
	{% if form.email.errors %} 
		<span class="error">{{ form.email.errors|join:", " }}</span>
	{% endif %}
	{% if form.password.errors %} 
		<span class="error">{{ form.password.errors|join:", " }}</span>
	{% endif %}
</p>
{% endif %}

{% if msg %}
<p class="errors">{{ msg }}</p>
{% endif %}

<div class="aligned">
	<form action="." method="post" accept-charset="utf-8">

		<div id="form-row"><label for="id_email">{% trans "Email" %}</label>{{ form.email }}</div>
		<div id="form-row"><label for="id_password">{% trans "Password" %}</label>{{ form.password }}</div>

        <p><input type="submit" value="{% trans "Change email" %}"></p>

	</form>
	</div>
{% endblock %}

server/django_authopenid/templates/authopenid/changeopenid.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h4 class="headblue">{% trans "Account: change OpenID URL" %}</h4>

<p>{% blocktrans %}This is where you can change your OpenID URL. Make sure you remember it!{% endblocktrans %}</p>
{% if form.errors %}
<p class="errors">{% trans "Please correct errors below:" %}<br />
	{% if form.openid_url.errors %} 
		<span class="error">{{ form.openid_url.errors|join:", " }}</span>
	{% endif %}


</p>
{% endif %}
{% if msg %}
	<p class="errors">{{ msg }}</p>
{% endif %}

<div class="aligned">
	<form action="." method="post" accept-charset="utf-8">

		<div id="form-row"><label for="id_openid_url">{% trans "OpenID URL:" %}</label>{{ form.openid_url }}</div>
        <p><input type="submit" value="{% trans "Change OpenID" %}"></p>

	</form>
	</div>
{% endblock %}

server/django_authopenid/templates/authopenid/changepw.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
		
{% endblock %}



{% block content %}
<h4 class="headblue">{% trans "Account: change password" %}</h4>

<p>{% blocktrans %}This is where you can change your password. Make sure you remember it!{% endblocktrans %}</p>
{% if form.errors %}
<p class="errors">{% trans "Please correct errors below:" %}<br />
{{ form.errors }}
</p>
{% endif %}

<div class="aligned">
	<form action="." method="post" accept-charset="utf-8">

		<div id="form-row"><label for="id_oldpw">{% trans "Current password" %}</label>{{ form.oldpw }}</div>
		<div id="form-row"><label for="id_password1">{% trans "New password" %}</label>{{ form.password1 }}</div>
		<div id="form-row"><label for="id_password2">{% trans "New password again" %}</label>{{ form.password2 }}</div>
        <p><input type="submit" value="{% trans "Change password" %}"></p>

	</form>
	</div>
{% endblock %}

server/django_authopenid/templates/authopenid/complete.html
{% extends "base.html" %}
{% load i18n %}



{% block head %}{% endblock %}


{% block content %}

	<div id="completetxt">
	<h1>{% trans "Your OpenID is verified! " %}</h1>
	{% blocktrans %}
	<p>Your OpenID can now be associated with a new or existing membership. You can change the association later in your preferences.</p>
	{% endblocktrans %}
	<br /><br />
	<h2>{% trans "Associate your OpenID" %}</h2>
	{% blocktrans %}
	<p>If you're joining <strong>Sitename</strong>, associate your OpenID with a new account. If you're already a member, associate with your existing account.</p>
	{% endblocktrans %}
	</div>

		
	
	{% if form1.errors %}
	<p class="errors">{% trans "Please correct errors below:" %}<br />
		{% if form1.username.errors %} 
			<span class="error">{{ form1.username.errors|join:", " }}</span>
		{% endif %}
		{% if form1.email.errors %} 
			<span class="error">{{ form1.email.errors|join:", " }}</span>
		{% endif %}
	</p>
	{% endif %}
	{% if form2.errors %}
	<p class="errors">{% trans "Please correct errors below:" %}<br />
		{% if form2.username.errors %} 
			<span class="error">{{ form2.username.errors|join:", " }}</span>
		{% endif %}
		{% if form2.password.errors %} 
			<span class="error">{{ form2.password.errors|join:", " }}</span>
		{% endif %}
	</p>
	{% endif %}

	<div class="login">
        <form name="fregister" action="{% url user_register %}" method="POST">
            {{ form.next }}
			<fieldset>
				<legend>{% trans "A new account" %}</legend>
				<div class="form-row"><label for "id_username">{% trans "Username" %}</label><br />{{ form1.username }}</div>
				<div class="form-row"><label for "id_email">{% trans "Email" %}</label><br />{{ form1.email }}</div>
				<div class="submit-row"><input type="submit" name="bnewaccount" value="Create account"></div>
				<hr class="clear" />
            	</fieldset>
		</form>
	</div>

	

	<div class="login">
		<h3></h3>
        <form name="fverify" action="{% url user_register %}" method="POST">
            {{ form.next }}
			<fieldset>
				<legend>{% trans "An exisiting account" %}</legend>
				<div class="form-row"><label for "id_username">{% trans "Username" %}</label><br />{{ form2.username }}</div>
				<div class="form-row"><label for "id_passwordl">{% trans "Password" %}</label><br />{{ form2.password }}</div>
				<div class="submit-row"><input type="submit" name="bverify" value="Verify"></div>
			</fieldset>
		</form>
	</div>
{% endblock %}

	

server/django_authopenid/templates/authopenid/delete.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
<h4 class="headblue">{% trans "Account: delete account" %}</h4>

<p class="settings-descr">{% blocktrans %}Note: After deleting your account, anyone will be able to register this username.{% endblocktrans %}</p>
{% if form.errors %}
<p class="errors">{% trans "Please correct errors below:" %}<br />
	{% if form.confirm.errors %} 
    <span class="error">{% trans "Check confirm box, if you want delete your account." %}</span><br />
	{% endif %}
	{% if form.password.errors %} 
    <span class="error">{% trans "Password:" %} {{ form.password.errors|join:", " }}</span>
	{% endif %}
</p>
{% endif %}
{% if msg %}
<p class="errors">{% trans "Please correct errors below:" %}<br />
    <span class="error">{{ msg }}</span>
    </p>
{% endif %}
<div class="aligned">
	<form action="." method="post" accept-charset="utf-8">

        <div id="form-row"> {{ form.confirm }} {% trans "I am sure I want to delete my account." %}</div>
        <div id="form-row"><label for="id_password">{% trans "Password/OpenID URL" %}</label>{{ form.password }} {% trans "(required for your security)" %}</div>

        <p><input type="submit" value="{% trans "Delete account permanently" %}"></p>

	</form>
	</div>
{% endblock %}

server/django_authopenid/templates/authopenid/failure.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
  "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <title>OpenID failed</title>
</head>
<body>
<h1>OpenID failed</h1>

<p>{{ message|escape }}</p>

</body>
</html>

server/django_authopenid/templates/authopenid/sendpw.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
<h4 class="headblue">{% trans "Account: Send a new password" %}</h4>

<p class="settings-descr">{% blocktrans %}Lost your password ? Here you can ask to reset your password. Enter the username you use  and you will get a confirmation email with your new password. This new password will be activated only after you have clicked on the link in the email.{% endblocktrans %}</p>
{% if form.errors %}
<p class="errors">{% trans "Please correct errors below:" %}<br />
	{% if form.username.errors %} 
		<span class="error">{{ form.username.errors|join:", " }}</span>
	{% endif %}
</p>
{% endif %}
{% if msg %}
<br /
<span class="error">{{ msg }}</span>
{% endif %}

<div class="aligned">
	<form action="." method="post" accept-charset="utf-8">
		<div id="form-row"><label for="id_username">{% trans "Username" %}</label>{{ form.username }}</div>

        <p><input type="submit" value="{% trans "Send new password" %}"></p>

	</form>
	</div>
{% endblock %}

server/django_authopenid/templates/authopenid/settings.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
<style type="text/css" media="screen">
	dt, dd { padding:0 0 0.35em 0; }
	dt { float: left; width: 21ex;  }
	dd { margin-left: 23ex;  }
	
	#settings-options, #settings-intro { padding: 4em 1.5em;}
	#settings-options { min-height: 300px; border-left: 1px solid #333;}
	
	#settings-options h5 { font-weight: bold;}
</style>
{% endblock %}

{% block content %}
<div id="settings-intro">
	


    <h4><strong>{{ user.username }}</strong> {% trans "Settings" %}</h4>
    {% blocktrans %}
    <p>This is where you can make changes to your account.</p>

    {% endblocktrans %}
</div>

<div id="settings-options">
	{% if msg %}
		<p class="error">{{ msg }}</p>
	{% endif %}
    <h5>{% trans "Account" %}</h5>
	<dl>
        <dt>» <a href="{% url user_changepw %}">{% trans "change password" %}</a></dt>
        <dd>{% trans "Give your  account a new password." %}</dd>
        <dt>» <a href="{% url user_changeemail %}">{% trans "change email" %}</a></dt>
        <dd>{% trans "Add or update the email address associated with your account." %}</dd>
        {% if is_openid %}
        <dt>» <a href="{% url user_changeopenid %}">{% trans "change openid url" %}</a></dt>
        <dd>{% trans "Change openid associated to your account" %}</dd>
        {% endif %}
        
        <dt>» <a href="{% url user_delete %}">{% trans "delete account" %}</a></dt>
        <dd>{% trans "Erase your username and all your data from website" %}</dd>
	</dl>
</div>
{% endblock %}

server/django_authopenid/templates/authopenid/signin.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}


{% endblock %}


{% block content %}
{% if msg %}
<br />
	<p class="warning">{{ msg }}</p>
{% endif %}
{% if form1.errors %}
<p class="errors">{% trans "Please correct errors below:" %}<br />
	{% if form1.username.errors %} 
		<span class="error">{{ form1.username.errors|join:", " }}</span>
	{% endif %}
	{% if form1.password.errors %} 
		<span class="error">{{ form1.password.errors|join:", " }}</span>
	{% endif %}
</p>
{% endif %}
<div class="login">

    <form name="fauth" action="{% url user_signin %}" method="post">
        {{ form1.next }}
	<fieldset>
		<legend>{% trans "Sign In Using Your Account ID" %}</legend>
		<div class="form-row"><label for="id_username">{% trans "Username:" %}</label><br />{{ form1.username }}</div>
		<div class="form-row"><label for="id_password">{% trans "Password" %}</label><br />{{ form1.password }}</div>
        <div class="submit-row"><input type="submit" name="blogin" value="{% trans "Sign in" %}"> </div>
        <div>&nbsp;&nbsp;<a href="{{ sendpw_url }}">{% trans "Lost your password ?" %}</a></div>
	</fieldset>	
</form>

<br />
<form name="fopenid" action="{% url user_signin %}" method="post">
    {{ form2.next }}
	<fieldset>
		<legend>{% trans "Sign In Using Your OpenID URL" %}</legend>
        <div class="form-row"><label for="id_openid_ul">{% trans "OpenId URL :" %}</label><br />{{ form2.openid_url }}</div>
        <div class="submit-row "><input name="bsignin" type="submit" value="{% trans "Sign in with OpenID" %}"></div>
		
	</fieldset>
</form>	
</div>	
{% endblock %}

server/django_authopenid/templates/authopenid/signup.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<div class="jointxt">
    {% blocktrans %}
    <h1>Join</h1>
    <p>There are two ways to join: with an email + username, or with OpenID.<br />Enter information only for the type of sign up you want to do.</p>
    {% endblocktrans %}
	<br />
	<br />
    <h2 class="signup">{% trans "Regular Signup" %}</h2>
    {% if form.errors %}
    <p class="errors">{% trans "Please correct errors below:" %}<br />
    {% if form.username.errors %} 
    <span class="error">{{ form.username.errors|join:", " }}</span>
    {% endif %}
    {% if form.email.errors %} 
    <span class="error">{{ form.email.errors|join:", " }}</span>
    {% endif %}
    {% if form.password2.errors %} 
    <span class="error">{{ form.password2.errors|join:", " }}</span>
    {% endif %}
    </p>
    {% endif %}
</div>
    <form action="{% url user_signup %}" method="post" accept-charset="utf-8">	
        <div class="form-row"><label for="id_username">{% trans "Choose a Username:" %}</label><br />{{ form.username }}</div>

        <div class="form-row"><label for="id_email">{% trans "Enter Your Email Address:" %}</label><br />{{ form.email }}</div>
        <div class="form-row"><label for="id_password1">{% trans "Choose a Password:" %}</label><br />{{ form.password1 }}</div>
        <div class="form-row"><label for="id_password2">{% trans "Confirm Your Password:" %}</label><br />{{ form.password2 }}</div>

        <div class="submit-row"><input type="submit" value="{% trans "Sign up" %}" /></div>
        <br />
    </form>
<br />
    <h2 class="signup">{% trans "OpenID Signup" %}</h2>
    <form name="fopenid" action="{% url user_signin %}" method="post">
        <div class="form-row">{{ form2.openid_url }}</div>
        <div class="submit-row "><input name="bsignin" type="submit" value="{% trans "Sign in with OpenID" %}"></div>
    </form>
{% endblock %}